---
# https://hub.docker.com/_/mongo/

mongo:
  image: mongo:3.2.12
  command: "mongod --httpinterface"
  ports:
    - "$mongo_port$:27017"

mongoexpress:
  image: mongo-express
  links:
    - mongo:mongo
  ports:
    - "8081:8081"
